---

spring:
  profiles: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-dev
    driverClassName: com.mysql.cj.jdbc.Driver
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

---

spring:
  profiles: qa
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    driverClassName: com.mysql.cj.jdbc.Driver
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: prod
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    driverClassName: com.mysql.cj.jdbc.Driver
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

---

welcome:
  message: Welcome to my Spring Boot project.!
server:
  port: '8082'

spring:
  profiles:
    active: qa